More changes to improve flags BLAS++ and LAPACK++

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -249,8 +249,13 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        sharedlib: [ ON, OFF ]
+        sharedlib: [ OFF, ON ]
         lapackpp: [ OFF ]
+        optblas: [ OFF, ON ]
+        optlapack: [ OFF, ON ]
+        exclude:
+          - optblas: ON
+            optlapack: ON
     
     steps:
     
@@ -261,12 +266,9 @@ jobs:
       uses: seanmiddleditch/gha-setup-ninja@16b940825621068d98711680b6c3ff92201f8fc0 # v3
     
     - name: Install the Basics
-      # Adding some noise to the system: libopenblas-dev liblapack-dev should not
-      # be linked to BLAS++ or LAPACK++.
       run: |
         sudo apt update
-        sudo apt install -y cmake gfortran
-        sudo apt purge libopenblas-dev liblapack-dev
+        sudo apt install -y cmake gfortran libopenblas-dev
 
     - name: Configure CMake
       run: >
@@ -279,26 +281,39 @@ jobs:
         -D BUILD_SHARED_LIBS:BOOL=${{ matrix.sharedlib }}
         -D BLAS++:BOOL=ON
         -D LAPACK++:BOOL=${{ matrix.lapackpp }}
+        -D USE_OPTIMIZED_BLAS:BOOL=${{ matrix.optblas }}
+        -D USE_OPTIMIZED_LAPACK:BOOL=${{ matrix.optlapack }}
 
     - name: Build
       run: cmake --build build --config ${{env.BUILD_TYPE}}
 
-    - name: Check dependencies of BLAS++
+    - name: Check dependencies of BLAS++ on BLAS and LAPACK
       working-directory: ${{github.workspace}}/build
       run: |
-        blaspp_blas=$(cat lib/cmake/blaspp/blasppConfig.cmake | grep "${{github.workspace}}/build/lib/libblas" | { grep -v grep || true; })
-        echo "blaspp_blas: $blaspp_blas"
-        if [[ -z $blaspp_blas ]]; then
-          echo "BLAS++ dependency to BLAS is not correct!"
-          echo "CMake could not find ${{github.workspace}}/build/lib/libblas in lib/cmake/blaspp/blasppConfig.cmake"
-          exit 1
-        fi
-        blaspp_lapack=$(cat lib/cmake/blaspp/blasppConfig.cmake | grep "${{github.workspace}}/build/lib/liblapack" | { grep -v grep || true; })
-        echo "blaspp_lapack: $blaspp_lapack"
-        if [[ -z $blaspp_lapack ]]; then
-          echo "BLAS++ dependency to LAPACK is not correct!"
-          echo "CMake could not find ${{github.workspace}}/build/lib/liblapack in lib/cmake/blaspp/blasppConfig.cmake"
-          exit 1
+        configFile="lib/cmake/blaspp/blasppConfig.cmake"
+        if [[ ${{ matrix.optblas }} == 'ON' || ${{ matrix.optlapack }} == 'ON' ]]; then
+          if grep -q "openblas" $configFile; then
+            echo "BLAS++ dependency to openblas is correct."
+          else
+            echo "CMake could not find openblas in $configFile:"
+            cat $configFile
+            exit 1
+          fi
+        else
+          if grep -q "${{github.workspace}}/build/lib/libblas" $configFile; then
+            echo "BLAS++ dependency to BLAS is correct."
+          else
+            echo "CMake could not find ${{github.workspace}}/build/lib/libblas in $configFile:"
+            cat $configFile
+            exit 1
+          fi
+          if grep -q "${{github.workspace}}/build/lib/liblapack" $configFile; then
+            echo "BLAS++ dependency to LAPACK is correct."
+          else
+            echo "CMake could not find ${{github.workspace}}/build/lib/liblapack in $configFile:"
+            cat $configFile
+            exit 1
+          fi
         fi
 
     - name: Install
